price1 = input('가격을 입력하세요:')
num1 = input('개수를 입력하세요:')
print(type(price1))
print(type(num1))
price2=int(price1)
num2=int(num1)
print(type(price2))
print(type(num2))
#sum = int(price1)*int(num1)
sum=price2*num2
print('총액은', sum, "입니다")
