# Generated by Django 4.1.1 on 2022-10-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBTest',
            fields=[ #id는 우리가 설정해주지 않았는데 자동으로 생성해준 것임.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
